/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.savagelearning.machete;

import org.junit.Test;
import static org.junit.Assert.*;

public class MacheteApplicationTest {
    @Test public void testAppHasAGreeting() {
        var classUnderTest = new MacheteApplication();
        assertNotNull("app should have a greeting", classUnderTest.getName());
    }
}
