/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.savagelearning.machete;

import com.savagelearning.machete.resources.HelloWorldResource;
import io.dropwizard.Application;
import io.dropwizard.db.DataSourceFactory;
import io.dropwizard.migrations.MigrationsBundle;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
//import com.example.helloworld.resources.HelloWorldResource;
//import com.example.helloworld.health.TemplateHealthCheck;

public class MacheteApplication extends Application<MacheteConfiguration> {
    public static void main(String[] args) throws Exception {
        new MacheteApplication().run(args);
    }

    @Override
    public String getName() {
        return "hello-world";
    }

    @Override
    public void initialize(Bootstrap<MacheteConfiguration> bootstrap) {
        bootstrap.addBundle(new MigrationsBundle<MacheteConfiguration>() {
            @Override
            public DataSourceFactory getDataSourceFactory(MacheteConfiguration configuration) {
                return configuration.getDataSourceFactory();
            }
        });
    }

    @Override
    public void run(MacheteConfiguration configuration,
                    Environment environment) {
        final var resource = new HelloWorldResource(
            configuration.getTemplate(),
            configuration.getDefaultName()
        );
        environment.jersey().register(resource);
    }

}
